name: Build and deploy to staging when pull request is created

on:
  push:
    branches:
      - no

jobs:
  build-and-deploy:
    name: Deploy to staging environment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
        architecture: x64

    - name: Auth gcloud CLI for image-store
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

    - name: Configure docker to use the gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker eu.gcr.io

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: eu.gcr.io/digdir-fdk-infra/concept-catalog-etl
        flavor: |
          latest=false
        tags: |
          type=raw,value=staging_latest
          type=raw,value=${{ github.sha }},priority=1000
          type=ref,event=branch

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha, mode=max
        build-args:  |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

    - name: Apply Helm template
      run: |
        helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/digdir-fdk-infra/concept-catalog-etl:$GITHUB_SHA" \
        -f ./helm-sources/values/staging.yaml \
        ./helm-sources/ > ./kubectlapply.yaml
        chmod o+w ./kubectlapply.yaml
        cat kubectlapply.yaml

    - name: Auth gcloud CLI for deploy
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}

    - name: Get credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: digdir-fdk-dev
        location: europe-north1-a

    - name: Deploy to GCP
      run: |
        kubectl apply -f ./kubectlapply.yaml --force
